### ISSUE TITLE
How to install ?

### ISSUE THREAD

**Issue by Hanfrey** [anyx/LoginGateBundle#1]
Hello, i dont get it working. Is this compatible with symfony 2.7?

1. composer require anyx/login-gate-bundle
2. noticed that my parameters.yml is set to default.
3. Added the "new Anyx\LoginGateBundle\LoginGateBundle()," to the AppKernel
4. Added the login_gate settings to the config.yml and security.yml
5. tried to login
6 Attempted to load Class BruteForceAttemptListener from Acme\BestBundle\Listener\

There is no Namespace like this, and in the Bundle i cant find that Class.

**Comment by anyx** [comment]
@Hanfrey 
Acme\BestBundle\Listener\BruteForceAttemptListener - this is an example. 
You should register you own listener, if you need to do something when bruteforce was detected.

**Comment by Hanfrey** [comment]
Thanks for the fast response.
I added my own Listener which should dump something if its hit. But its not working like i thought:

If i add the success_handler the login is not working anymore. I commented and tried to bruteforce the login which hit the event.But i get the following error:

The autoloader expected class "AppBundle\EventListener\BruteForceAttemptListener" to be defined in file "src\AppBundle\EventListener\BruteForceAttemptListener.php". The file was found but the class was not in it, the class name or namespace probably has a typo.
```yml
          class: AppBundle\EventListener\BruteForceAttemptListener
          tags:
              - { name: kernel.event_listener, event: security.brute_force_attempt, method: onBruteForceAttempt }
````

The class:
```php
<?
namespace AppBundle\EventListener;

class BruteForceAttemptListener
{
public function onBruteForceAttempt( )
{
dump("got it!");
}
}
```
Any Idea? Thanks!
